### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by MrIago** [freenetwork/investing.com.economic-calendar#1]
n = Investing()
n.news()
**Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    n.news()
  File "C:\Users\Mr Iago\Desktop\investing.com.economic-calendar-master\investing.py", line 25, in news
    news['time'] = int(datetime.datetime.strptime(row.attrs['data-event-datetime'], '%Y/%m/%d %H:%M:%S').strftime('%s'))
ValueError: Invalid format string**

**Comment by freenetwork** [comment]
Indeed, there was a problem. I have not tested on Windows. I corrected and added a couple more things.

**Comment by MrIago** [comment]
Thanks man! How does the IqOption api works?

**Comment by freenetwork** [comment]
> Thanks man! How does the IqOption api works?

The project stopped because iqoption, does not work in Russia any more. I could continue the project, but the account is necessary.
